### PR TITLE
Update office-online-server.md

### PR DESCRIPTION
**Pull request by tseward**
Update for #3. Going through O365 Support is not an option. Customers must contact the licensing support center as noted for those with "VL Open". Per O365 Support (Case #11996225 if you need it), you must have a volume license agreement and having O365-only licenses is not sufficient:

"Upon further research it seems you will need to have a volume license account/agreement. Once you have this, you will be able to access VLSC."

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@JasonH-Msft @lorenahuangliu Can I merge this?

**Comment by JasonH-Msft** [comment]
@lorenahuangliu  could you take a look at this for approval?  Or may need to re-engage conversation with licensing folks...

**Comment by lorenahuangliu** [comment]
No, the way to access still stands. We have provided support agents with download links when they have the correct license to have OOS. They do not need access to VLSC to do so.

**Comment by tseward** [comment]
@lorenahuangliu After spending a few hours engaging with them, that doesn't seem to be the case or the agent I received was misinformed. What are the magic key words to get the OOS ISO without going through the VLSC?

**Comment by JasonH-Msft** [comment]
Support engineers should be able to search our Service Desk tool for "download Office Online Server" which returns at the top of the list, (internal) KB 4054141 (which describes the process to provide a download link).

**Pull request closed without merging**
